DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS queue;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fk_user INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_user) REFERENCES user (id)
);